//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type CallsignLookup struct {
	Callsign         string `sql:"primary_key"`
	QueryCallsign    string
	Status           string
	SavedAtUnixMs    int64
	Error            string
	ProvidersChecked string
	RecordCallsign   *string
	Country          *string
	CqZone           *string
	Grid             *string
	ItuZone          *string
	Name             *string
	Nickname         *string
	QrzURL           *string
	Qth              *string
	State            *string
}
