//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Qso struct {
	ID                string `sql:"primary_key"`
	StationCallsign   string
	Callsign          string
	StartedAtUnixMs   int64
	FrequencyHz       *int64
	Mode              string
	Submode           string
	RstSent           string
	RstReceived       string
	ExchangeSent      string
	ExchangeReceived  string
	Name              string
	Qth               string
	Notes             string
	QrzSyncedAtUnixMs *int64
	CreatedAtUnixMs   int64
	UpdatedAtUnixMs   int64
	QrzLogID          *int64
}
