// Package artifacts provides access to model files generated by Python.
package artifacts

import (
	"embed"
	"encoding/binary"
	"fmt"
	"math"
)

//go:embed generated/weights/*.f32
var weights embed.FS

func LoadFloat32(name string, count int) ([]float32, error) {
	path := "generated/weights/" + name

	data, err := weights.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read embedded model tensor %q: %w", path, err)
	}

	expectedBytes := count * 4
	if len(data) != expectedBytes {
		return nil, fmt.Errorf(
			"%s: got %d bytes, expected %d",
			path,
			len(data),
			expectedBytes,
		)
	}

	values := make([]float32, count)
	for index := range values {
		offset := index * 4
		bits := binary.LittleEndian.Uint32(data[offset : offset+4])
		values[index] = math.Float32frombits(bits)
	}

	return values, nil
}
