//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var ApplicationSettings = newApplicationSettingsTable("", "application_settings", "")

type applicationSettingsTable struct {
	sqlite.Table

	// Columns
	ID                 sqlite.ColumnInteger
	StationCallsign    sqlite.ColumnString
	QrzPassword        sqlite.ColumnString
	QrzAPIKey          sqlite.ColumnString
	MorseInputDeviceID sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type ApplicationSettingsTable struct {
	applicationSettingsTable

	EXCLUDED applicationSettingsTable
}

// AS creates new ApplicationSettingsTable with assigned alias
func (a ApplicationSettingsTable) AS(alias string) *ApplicationSettingsTable {
	return newApplicationSettingsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ApplicationSettingsTable with assigned schema name
func (a ApplicationSettingsTable) FromSchema(schemaName string) *ApplicationSettingsTable {
	return newApplicationSettingsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ApplicationSettingsTable with assigned table prefix
func (a ApplicationSettingsTable) WithPrefix(prefix string) *ApplicationSettingsTable {
	return newApplicationSettingsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ApplicationSettingsTable with assigned table suffix
func (a ApplicationSettingsTable) WithSuffix(suffix string) *ApplicationSettingsTable {
	return newApplicationSettingsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newApplicationSettingsTable(schemaName, tableName, alias string) *ApplicationSettingsTable {
	return &ApplicationSettingsTable{
		applicationSettingsTable: newApplicationSettingsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                 newApplicationSettingsTableImpl("", "excluded", ""),
	}
}

func newApplicationSettingsTableImpl(schemaName, tableName, alias string) applicationSettingsTable {
	var (
		IDColumn                 = sqlite.IntegerColumn("id")
		StationCallsignColumn    = sqlite.StringColumn("station_callsign")
		QrzPasswordColumn        = sqlite.StringColumn("qrz_password")
		QrzAPIKeyColumn          = sqlite.StringColumn("qrz_api_key")
		MorseInputDeviceIDColumn = sqlite.StringColumn("morse_input_device_id")
		allColumns               = sqlite.ColumnList{IDColumn, StationCallsignColumn, QrzPasswordColumn, QrzAPIKeyColumn, MorseInputDeviceIDColumn}
		mutableColumns           = sqlite.ColumnList{StationCallsignColumn, QrzPasswordColumn, QrzAPIKeyColumn, MorseInputDeviceIDColumn}
		defaultColumns           = sqlite.ColumnList{IDColumn, StationCallsignColumn, QrzPasswordColumn, QrzAPIKeyColumn, MorseInputDeviceIDColumn}
	)

	return applicationSettingsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                 IDColumn,
		StationCallsign:    StationCallsignColumn,
		QrzPassword:        QrzPasswordColumn,
		QrzAPIKey:          QrzAPIKeyColumn,
		MorseInputDeviceID: MorseInputDeviceIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
