//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var CallsignLookup = newCallsignLookupTable("", "callsign_lookup", "")

type callsignLookupTable struct {
	sqlite.Table

	// Columns
	Callsign         sqlite.ColumnString
	QueryCallsign    sqlite.ColumnString
	Status           sqlite.ColumnString
	SavedAtUnixMs    sqlite.ColumnInteger
	Error            sqlite.ColumnString
	ProvidersChecked sqlite.ColumnString
	RecordCallsign   sqlite.ColumnString
	Country          sqlite.ColumnString
	CqZone           sqlite.ColumnString
	Grid             sqlite.ColumnString
	ItuZone          sqlite.ColumnString
	Name             sqlite.ColumnString
	Nickname         sqlite.ColumnString
	QrzURL           sqlite.ColumnString
	Qth              sqlite.ColumnString
	State            sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type CallsignLookupTable struct {
	callsignLookupTable

	EXCLUDED callsignLookupTable
}

// AS creates new CallsignLookupTable with assigned alias
func (a CallsignLookupTable) AS(alias string) *CallsignLookupTable {
	return newCallsignLookupTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CallsignLookupTable with assigned schema name
func (a CallsignLookupTable) FromSchema(schemaName string) *CallsignLookupTable {
	return newCallsignLookupTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CallsignLookupTable with assigned table prefix
func (a CallsignLookupTable) WithPrefix(prefix string) *CallsignLookupTable {
	return newCallsignLookupTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CallsignLookupTable with assigned table suffix
func (a CallsignLookupTable) WithSuffix(suffix string) *CallsignLookupTable {
	return newCallsignLookupTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCallsignLookupTable(schemaName, tableName, alias string) *CallsignLookupTable {
	return &CallsignLookupTable{
		callsignLookupTable: newCallsignLookupTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newCallsignLookupTableImpl("", "excluded", ""),
	}
}

func newCallsignLookupTableImpl(schemaName, tableName, alias string) callsignLookupTable {
	var (
		CallsignColumn         = sqlite.StringColumn("callsign")
		QueryCallsignColumn    = sqlite.StringColumn("query_callsign")
		StatusColumn           = sqlite.StringColumn("status")
		SavedAtUnixMsColumn    = sqlite.IntegerColumn("saved_at_unix_ms")
		ErrorColumn            = sqlite.StringColumn("error")
		ProvidersCheckedColumn = sqlite.StringColumn("providers_checked")
		RecordCallsignColumn   = sqlite.StringColumn("record_callsign")
		CountryColumn          = sqlite.StringColumn("country")
		CqZoneColumn           = sqlite.StringColumn("cq_zone")
		GridColumn             = sqlite.StringColumn("grid")
		ItuZoneColumn          = sqlite.StringColumn("itu_zone")
		NameColumn             = sqlite.StringColumn("name")
		NicknameColumn         = sqlite.StringColumn("nickname")
		QrzURLColumn           = sqlite.StringColumn("qrz_url")
		QthColumn              = sqlite.StringColumn("qth")
		StateColumn            = sqlite.StringColumn("state")
		allColumns             = sqlite.ColumnList{CallsignColumn, QueryCallsignColumn, StatusColumn, SavedAtUnixMsColumn, ErrorColumn, ProvidersCheckedColumn, RecordCallsignColumn, CountryColumn, CqZoneColumn, GridColumn, ItuZoneColumn, NameColumn, NicknameColumn, QrzURLColumn, QthColumn, StateColumn}
		mutableColumns         = sqlite.ColumnList{QueryCallsignColumn, StatusColumn, SavedAtUnixMsColumn, ErrorColumn, ProvidersCheckedColumn, RecordCallsignColumn, CountryColumn, CqZoneColumn, GridColumn, ItuZoneColumn, NameColumn, NicknameColumn, QrzURLColumn, QthColumn, StateColumn}
		defaultColumns         = sqlite.ColumnList{ErrorColumn, ProvidersCheckedColumn}
	)

	return callsignLookupTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Callsign:         CallsignColumn,
		QueryCallsign:    QueryCallsignColumn,
		Status:           StatusColumn,
		SavedAtUnixMs:    SavedAtUnixMsColumn,
		Error:            ErrorColumn,
		ProvidersChecked: ProvidersCheckedColumn,
		RecordCallsign:   RecordCallsignColumn,
		Country:          CountryColumn,
		CqZone:           CqZoneColumn,
		Grid:             GridColumn,
		ItuZone:          ItuZoneColumn,
		Name:             NameColumn,
		Nickname:         NicknameColumn,
		QrzURL:           QrzURLColumn,
		Qth:              QthColumn,
		State:            StateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
