//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Qso = newQsoTable("", "qso", "")

type qsoTable struct {
	sqlite.Table

	// Columns
	ID                sqlite.ColumnString
	StationCallsign   sqlite.ColumnString
	Callsign          sqlite.ColumnString
	StartedAtUnixMs   sqlite.ColumnInteger
	FrequencyHz       sqlite.ColumnInteger
	Mode              sqlite.ColumnString
	Submode           sqlite.ColumnString
	RstSent           sqlite.ColumnString
	RstReceived       sqlite.ColumnString
	ExchangeSent      sqlite.ColumnString
	ExchangeReceived  sqlite.ColumnString
	Name              sqlite.ColumnString
	Qth               sqlite.ColumnString
	Notes             sqlite.ColumnString
	QrzSyncedAtUnixMs sqlite.ColumnInteger
	CreatedAtUnixMs   sqlite.ColumnInteger
	UpdatedAtUnixMs   sqlite.ColumnInteger
	QrzLogID          sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type QsoTable struct {
	qsoTable

	EXCLUDED qsoTable
}

// AS creates new QsoTable with assigned alias
func (a QsoTable) AS(alias string) *QsoTable {
	return newQsoTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new QsoTable with assigned schema name
func (a QsoTable) FromSchema(schemaName string) *QsoTable {
	return newQsoTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new QsoTable with assigned table prefix
func (a QsoTable) WithPrefix(prefix string) *QsoTable {
	return newQsoTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new QsoTable with assigned table suffix
func (a QsoTable) WithSuffix(suffix string) *QsoTable {
	return newQsoTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newQsoTable(schemaName, tableName, alias string) *QsoTable {
	return &QsoTable{
		qsoTable: newQsoTableImpl(schemaName, tableName, alias),
		EXCLUDED: newQsoTableImpl("", "excluded", ""),
	}
}

func newQsoTableImpl(schemaName, tableName, alias string) qsoTable {
	var (
		IDColumn                = sqlite.StringColumn("id")
		StationCallsignColumn   = sqlite.StringColumn("station_callsign")
		CallsignColumn          = sqlite.StringColumn("callsign")
		StartedAtUnixMsColumn   = sqlite.IntegerColumn("started_at_unix_ms")
		FrequencyHzColumn       = sqlite.IntegerColumn("frequency_hz")
		ModeColumn              = sqlite.StringColumn("mode")
		SubmodeColumn           = sqlite.StringColumn("submode")
		RstSentColumn           = sqlite.StringColumn("rst_sent")
		RstReceivedColumn       = sqlite.StringColumn("rst_received")
		ExchangeSentColumn      = sqlite.StringColumn("exchange_sent")
		ExchangeReceivedColumn  = sqlite.StringColumn("exchange_received")
		NameColumn              = sqlite.StringColumn("name")
		QthColumn               = sqlite.StringColumn("qth")
		NotesColumn             = sqlite.StringColumn("notes")
		QrzSyncedAtUnixMsColumn = sqlite.IntegerColumn("qrz_synced_at_unix_ms")
		CreatedAtUnixMsColumn   = sqlite.IntegerColumn("created_at_unix_ms")
		UpdatedAtUnixMsColumn   = sqlite.IntegerColumn("updated_at_unix_ms")
		QrzLogIDColumn          = sqlite.IntegerColumn("qrz_log_id")
		allColumns              = sqlite.ColumnList{IDColumn, StationCallsignColumn, CallsignColumn, StartedAtUnixMsColumn, FrequencyHzColumn, ModeColumn, SubmodeColumn, RstSentColumn, RstReceivedColumn, ExchangeSentColumn, ExchangeReceivedColumn, NameColumn, QthColumn, NotesColumn, QrzSyncedAtUnixMsColumn, CreatedAtUnixMsColumn, UpdatedAtUnixMsColumn, QrzLogIDColumn}
		mutableColumns          = sqlite.ColumnList{StationCallsignColumn, CallsignColumn, StartedAtUnixMsColumn, FrequencyHzColumn, ModeColumn, SubmodeColumn, RstSentColumn, RstReceivedColumn, ExchangeSentColumn, ExchangeReceivedColumn, NameColumn, QthColumn, NotesColumn, QrzSyncedAtUnixMsColumn, CreatedAtUnixMsColumn, UpdatedAtUnixMsColumn, QrzLogIDColumn}
		defaultColumns          = sqlite.ColumnList{SubmodeColumn, RstSentColumn, RstReceivedColumn, ExchangeSentColumn, ExchangeReceivedColumn, NameColumn, QthColumn, NotesColumn}
	)

	return qsoTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                IDColumn,
		StationCallsign:   StationCallsignColumn,
		Callsign:          CallsignColumn,
		StartedAtUnixMs:   StartedAtUnixMsColumn,
		FrequencyHz:       FrequencyHzColumn,
		Mode:              ModeColumn,
		Submode:           SubmodeColumn,
		RstSent:           RstSentColumn,
		RstReceived:       RstReceivedColumn,
		ExchangeSent:      ExchangeSentColumn,
		ExchangeReceived:  ExchangeReceivedColumn,
		Name:              NameColumn,
		Qth:               QthColumn,
		Notes:             NotesColumn,
		QrzSyncedAtUnixMs: QrzSyncedAtUnixMsColumn,
		CreatedAtUnixMs:   CreatedAtUnixMsColumn,
		UpdatedAtUnixMs:   UpdatedAtUnixMsColumn,
		QrzLogID:          QrzLogIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
